apiVersion: v1
kind: Pod
metadata:
  name: tester
  namespace: argo-rollouts
spec:
  serviceAccountName: argo-rollouts-chainsaw
  terminationGracePeriodSeconds: 0
  containers:
  - name: chainsaw-test
    image: docker.io/library/chainsaw-test:tester
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "sleep infinity"]
